### ISSUE TITLE
As a developer of high performance software, I would like the time performance of the native sdot implementation to be comparable to that of the BLAS library

### ISSUE THREAD

**Issue by dlewissandy** [dlewissandy/lambda-blas#9]
The implementation of the sdot function performs poorly when compared to calling the CBLAS library. Investigate and implement opportunities for improvement in the Haskell code for example: increased strictness, reducing bound checking, inlining, explicit fusion...

**Comment by dlewissandy** [comment]
# BENCHMARK BASELINE
Attached is the benchmark report for the master branch prior to making any optimizations (SHA FAE283b).   Benchmarks were run on a Mac Pro (Late 2013) with a   3.7 GHz Quad-Core Intel Xeon E5 processor and running OS X 10.11.6 (15G1108).   Unless stated otherwise, all future benchmarks will be performed on that machine.

 [sdot benchmarks - fae283b.pdf](https://github.com/dlewissandy/blas/files/690366/sdot.benchmarks.-.fae283b.pdf)

As anticipated, the BLAS code is substantially faster (by a factor ~31) than the native Haskell implementation of the sdot algorithm, which in turn is substantially faster (by a factor of ~6) than the naive implementation.     It should be pointed out that these benchmarks ONLY COMPARE THE SPEED OF THE ALGORITHMS; marshaling time has been explicitly excluded.

**Comment by dlewissandy** [comment]
Things to try in optimization:
- [] Monomorphize hylomorphism function
- [] Perform strictness analysis and annotate for additional strictness as required
- [] Unboxing types/reduce reboxing of types
- [] Improved inlining of code
- [] Replace usage of multi-constructor types with single-constructor types (e.g. replace Maybe with integer tags)

**Comment by dlewissandy** [comment]
# BENCHMARK - NEW BASELINE
Due to ongoing issues with latency with OSX builds on Travis, I have switched to using a Linux computer as my primary development box, and as of a37a36 am switching to using the FORTRAN BLAS library instead of the Apple Accelerate framework version of CBLAS.     

Details of my linux box are as follows:
| ----------------- | --------------------- | 
| OS                         | Ubuntu Server 16.04 | 
| Processor Type    | Intel Core i5               | 
| Processor Speed | 2.0 GHz                      | 
| Memory                | 8 GB                           | 
| ----------------- | --------------------- |

The new baseline benchmarks for SHA a37a36ab27 are summarized below:

![screen shot 2017-01-23 at 8 29 41 am](https://cloud.githubusercontent.com/assets/8261149/22212590/1d0bf36a-e146-11e6-8411-9d2374d253e9.png)

We note that for vectors smaller than 10 the native Haskell implementation of the BLAS algorithm outperforms the FORTRAN implementation, however for larger vectors the FORTRAN version outperforms the native Haskell by almost 15x.   It is important to note that the time efficiency of the FORTRAN implementation is essentially independent of the vector size until vectors are larger than 10.   This localized O(1) time performance was not expected and may be some unaccounted overhead associated with the FORTRAN call.

**Comment by dlewissandy** [comment]
# THE IMPORTANCE OF COMPILER OPTIMIZATION
The current tip of the master branch (SHA a37a36ab) compiles the test suites, benchmarks, and library using the O2 compiler flag.   This compiler option applies the most aggressive set of safe compiler optimizations.   As a point of comparison, I have compiled the same commit using both -O0 (no optimization) and -02 optimization levels and have attached a comparison plot below:
![screen shot 2017-01-23 at 4 20 21 pm](https://cloud.githubusercontent.com/assets/8261149/22228746/fabf716e-e187-11e6-952a-b473b700ee26.png)

Vectors of lengths between 1 and 50,000 were simulated using each of the three sdot algorithms and each of the two optimization levels.   The average running time for each algorithm/vector length pair without optimization was plotted against the running time for the corresponding pair with compiler optimization enabled.    The dotted line represents identical performance under both optimization conditions, while the red/green shaded regions represent decreased/improved time performance with O0.    

As anticipated, the foreign FORTRAN calls are not significantly impacted by the compiler optimization because Haskell is merely calling an external object library.   All the observations for 
the FORTRAN BLAS benchmarks fall nearly on the diagonal line.

Compiler optimization leads to the greatest improvement in the performance of the naive code (between ~50 and 500 fold improvement), while the native Haskell implementation of sdot receives only a modest (between 20 and 50 fold) improvement in time performance.     This is not surprising; the hand-crafted nature of the native implementation of the sdot function may obfuscate opportunities for simplifications that could be applied to the naive function.    For a complete list of compiler optimizations, please see:  [GHC Documentation](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/using-optimisation.html#o-convenient-packages-of-optimisation-flags )

**Comment by dlewissandy** [comment]
# Haskell Really Likes Strict Single Constructor Data Types..
Because they can be unpacked into primitive (unboxed) types.   Unfortunately, our implementation of the hyloL function makes uses of functions that return Maybe (a two constructor type).    Although hyloL has been marked for inlining, the simplifier cannot see the obvious means to eliminate the maybe datatype.   Specifically, the hyloL function, sum5 and takeAndMul5 functions can be fused into a single recursive function that terminates when either of the two vector arguments are null.     SHA 5af7e5dff introduces a manually fused version of the hyloL function, as well as a few strictness annotations to improve the unpacking of the data in the Haskell core.    A performance of the refactored code to the code on the master branch is summarized in the following graphs:

![screen shot 2017-01-23 at 5 32 54 pm](https://cloud.githubusercontent.com/assets/8261149/22230375/066776d8-e192-11e6-9853-1dd39a64e951.png)
![screen shot 2017-01-23 at 5 33 23 pm](https://cloud.githubusercontent.com/assets/8261149/22230384/114a366c-e192-11e6-9597-ea4c2ddbaa48.png)

For vectors larger than 5, the time performance of the refactored code is substantially improved (by a factor of nearly 4), and for small vectors ( length less than ~25) outperforms the FORTRAN sdot implementation.   However, as the vectors become large, the FORTRAN outperforms the native implementation by a factor of 4x.

**Comment by dlewissandy** [comment]
# REDUCING EXPENSIVE VECTOR OPERATIONS
Although the performance of SHA 5af7e5dff was improved, it does not meet the target performance criteria for this milestone (within 2x of the FORTRAN implementation).    To understand the rationale for the next optimization, consider the following close-up of the time performance chart for SHA 5af7e5dff:

![screen shot 2017-01-23 at 6 22 35 pm](https://cloud.githubusercontent.com/assets/8261149/22231849/acf0bbe2-e19a-11e6-89a0-a01e13707e29.png)

For lengths up to 4, the time performance is identical (within error) to the time performance of the naive implementation.   However, for vectors of length 5, we have an abrupt jump of about 20nsec, and then periodically jumps of 20nsec for vectors of length (n+1)*5+1

By analyzing the guards in the native Haskell sdot function we can get a hint of what is going on:
* for vectors less than length 5, a special case solution is used that requires no calls to hyloL
* For vectors of length 5, the program makes one call to hyloL, but terminates on the first recursive step
* For vectors of length [ (n+1)*5+1 .. (n+2)*5 ] the program calls hyloL and terminates after the (n+1) recursive call.

Why is each recursive call so expensive?   All we are doing is testing the length of two vectors (which should be O(1)), dropping 5 elements from two vectors (also O(1)) and doing some arithmetic.   After inspecting the core, it turns out that all the work that we did in 5af7e5d to utilize unboxed types is being undone by the calls to the vector functions.    GHC has to repack the vector types before each of these calls at some expense.    The compiler is not clever enough to figure out how to refactor the hyloL function to eliminate the need to rebox the types.

To eliminate the repeated packing and unpacking of the vectors, commit 17276deef refactors the hylomorphism so that iterates over an element offset, rather that recursing over the tail of the vectors.   
![screen shot 2017-01-23 at 8 08 49 pm](https://cloud.githubusercontent.com/assets/8261149/22233789/caad09e4-e1a7-11e6-8d92-d64e4de55489.png)

We note that the time performance of the native implementation of the sdot algorithm now outperforms the BLAS implementation for vectors of any size, and outperforms the native implementation for some vector lengths greater than 20.    The average cost per recursive call to the hyloL function has been reduced to about 4.6nsec, however every datapoint that is divisible by 5 is LOWER than those adjacent to it by approximately 15nsec (where we would expect +/- 1ns).   We will address this next

**Comment by dlewissandy** [comment]
# PERFORMANCE WHEN VECTOR LENGTH INDIVISIBLE BY 5
In the previous post, we saw that when the vector length was divisible by 5, the special case code kicked in (the optimized version of hyloL) and resulted in a 4.6ns execution time per recursive call.   However, when the parameter n (a surrogate for the vector length) is not divisible by 5, there is a time performance penalty of nearly 20ns.    Inspection of the code provides little indication of the cause of the time penalty:

```haskell
        let subtotal = V.foldl1' (+) . V.take m . V.zipWith (*) sx $ sy
```

however, inspection of the core output (reformatted for human consumption) is more enlightening
```haskell
letrec { 
  loop = \ (i :: Int#) (index_X :: Int#) (index_Y :: Int#) (c :: Float#) ->
      case (<# i n) of 
        False -> c;
        True -> case (>=# index_X len_X) of
            False -> case (<# i n) of
                False -> c;
                True -> case (>=# index_Y len_Y) of 
                    False -> case readFloatOffAddr# ptr_X index_X of 
                       ( _ , x_i #) -> case readFloatOffAddr# ptr_Y index_Y of
                           ( _ , y_i ) -> 
                                loop (+# i 1#) (+# index_X 1#) (+# index_Y 1#)
                                    (plusFloat# c (timesFloat# x_i y_i))
                    True -> c
            True -> c
in loop 0# 0# 0# 0.0#
```

There are three potentially costly features of the way that the Haskell has been converted to core:
1)  The termination condition is evaluated twice (first on line 3 and again on line 6).   This is a result of the way that zip is applied to take in the original arguments.    
2) Bounds checks (lines 5 and 8) are being performed for both the vectors, despite the fact that we intended to dereference the elements without bounds checking.   Although we could (and probably should) use unsafeTake to remove the bounds checks on the take invocation, the use of zipWith will still reintroduce bounds checks into the core code.
3) The use of conditionals reintroduces the use of two constructor datatypes (in this case Bool), which have to be reconstructed before evaluation of the case statements.

I have replaced the zip / fold implementation with the function `sumprods`.   The core (again nicely reformatted for human consumption) is below:
```haskell
letrec 
    sumprods = \ (c :: Float#) (i :: Int#) ->
        case (<# i m) of
          False -> c;
          True ->
            case readFloatOffAddr# ptr_X i of (# _, x_i #) ->
                case readFloatOffAddr# ptr_Y i of (# _, y_i #) ->
                    sumprods (plusFloat# c (timesFloat# x_i y_i)) (+# i 1#)
sumprods 0# 0#
```
We can see that the bounds checks and redundant termination condition have all been eliminated.  Furthermore, all but one usage of the Bool datatype has been eliminated.   Time performance can be visualized in the graphs below:

![screen shot 2017-01-24 at 2 16 08 pm](https://cloud.githubusercontent.com/assets/8261149/22269319/bd88d5b6-e23f-11e6-8b1d-d77d0a5cf77a.png)
![screen shot 2017-01-24 at 2 14 39 pm](https://cloud.githubusercontent.com/assets/8261149/22269321/c081f46e-e23f-11e6-8c88-049f15d9ea3a.png)

As depicted, the time performance of the native algorithm is on par or better than the BLAS algorithm.   For small vectors the performance difference is large, and favors the native Haskell implementation by a factor of 10x.

**Comment by dlewissandy** [comment]
# The Final Special Case
The sdot algorithm supports an additional special case for when either incx or incy are not equal to one.   This allows the sdot algorithm to traverse either one or both of the vectors in steps that are larger than one, and (when negative) traverse in reverse order.   Learning from the optimizations applied to the other special cases above, I refactored this special case code to improve the time performance.    The charts below summarize the time performance after refactoring:

![screen shot 2017-01-24 at 7 49 08 pm](https://cloud.githubusercontent.com/assets/8261149/22277159/3c1ca640-e26e-11e6-8426-71e77965bf62.png)

As depicted, the native Haskell implementation for this corner case is on par or better than the FORTRAN sdot algorithm.   For small vectors the performance difference is large, and favors the native haskell implemenation by a factor of approximately 5x.

**Comment by dlewissandy** [comment]
Issue closed as completed after approval of pull request #30

**Comment by Traap** [comment]
@dlewissandy Nice summary!  Do you have a hypothesis regarding the curve's tail end?  It appears the there is a performance boost with vectors larger than 100K.  Of course, this might be just noise.

**Comment by dlewissandy** [comment]
The data is pretty noisy.   I would need to collect more data to be able to say anything definitive.
